name: Publish Package to npm

on:
  # Main branch trigger after version-bump
  workflow_run:
    workflows: ["Auto Version Bump"]
    branches: [main]
    types:
      - completed
  
  # PR branch trigger
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'package.json'
      - 'tsconfig.json'

jobs:
  publish:
    runs-on: ubuntu-latest
    # For workflow_run triggers, only run if the previous workflow succeeded
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
      
      - name: Generate version for PR
        id: version
        if: github.event_name == 'pull_request'
        run: |
          # Get base version from package.json
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          
          # Extract major version (first component)
          MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1)
          
          # Generate today's date in YYYYMMDD format 
          DATE=$(date +'%Y%m%d')
          
          # PR workflow - include PR number in version and tag
          PR_NUMBER="${{ github.event.pull_request.number }}"
          COMMIT_HASH=$(git rev-parse --short HEAD)
          
          # Format: major.date.patch-pr.number.hash
          VERSION="${MAJOR}.${DATE}.0-pr.${PR_NUMBER}.${COMMIT_HASH}"
          NPM_TAG="pr-${PR_NUMBER}"
          
          npm version $VERSION --no-git-tag-version
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "npm_tag=$NPM_TAG" >> $GITHUB_OUTPUT
      
      - name: Use release version for main
        id: main_version
        if: github.event_name == 'workflow_run'
        run: |
          # For main branch builds after version bump, use the latest tag
          LATEST_TAG=$(git describe --tags --abbrev=0)
          VERSION=${LATEST_TAG#v} # Remove 'v' prefix
          NPM_TAG="latest"
          
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "npm_tag=$NPM_TAG" >> $GITHUB_OUTPUT
      
      - name: Publish PR version to npm
        if: github.event_name == 'pull_request'
        run: npm publish --tag ${{ steps.version.outputs.npm_tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Publish main version to npm
        if: github.event_name == 'workflow_run'
        run: npm publish --tag ${{ steps.main_version.outputs.npm_tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Comment with installation instructions
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const version = '${{ steps.version.outputs.version }}';
            const tag = '${{ steps.version.outputs.npm_tag }}';
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `📦 Published version \`${version}\` to npm.
              
              Install with:
              \`\`\`bash
              npm install @open-game-system/store-bridge@${tag}
              \`\`\`
              `
            }); 